name: Test and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Run unit tests
      run: pio test

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Build project
      run: pio run

    - name: Upload firmware
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .pio/build/*/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}