name: Test and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        version: 0.19.0

    - name: Install dependencies
      run: |
        arduino-cli lib install "ArduinoUnit"

    - name: Compile example sketch
      run: arduino-cli compile --fqbn esp8266:esp8266:generic examples/main.cpp

    - name: Run unit tests
      run: arduino-cli test --fqbn esp8266:esp8266:generic test/test_espmultilogger.cpp

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    # ^^^ Match the branch name with your triggers

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/esp8266.esp8266.generic/examples/main.cpp.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}